# Generated by Django 2.2.24 on 2021-11-22 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delphius', '0002_employee_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Del_connect_Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_frame', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='municipal_approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='public_participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='solution_shareable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delphius_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, null=True)),
                ('cont_person', models.CharField(max_length=200, null=True)),
                ('cont_no', models.CharField(max_length=13, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200, null=True)),
                ('solution_type', models.CharField(max_length=200, null=True)),
                ('est_duration', models.CharField(max_length=200, null=True)),
                ('est_municipal', models.CharField(max_length=200, null=True)),
                ('est_power_conn', models.CharField(max_length=200, null=True)),
                ('est_solu_cost', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('delconn_interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delphius.Del_connect_Interest')),
                ('dusk_dawn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delphius.Duration')),
                ('municipal_appr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delphius.municipal_approval')),
                ('operator_interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delphius.Operator')),
                ('p_participation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delphius.public_participation')),
                ('participation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delphius.Participation')),
                ('solution_sh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delphius.solution_shareable')),
            ],
        ),
    ]
