# Generated by Django 2.2.24 on 2021-11-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('id_no', models.CharField(max_length=200, null=True)),
                ('job_type', models.CharField(max_length=13, null=True)),
                ('job_description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
