# Generated by Django 2.2.24 on 2021-11-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelliview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcart',
            name='job_description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
