# Generated by Django 2.2.24 on 2021-11-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelliview', '0002_auto_20211119_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcart',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
